name: navbarhomeaboutcalculatorapp
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pandabar: ^0.1.2
  shared_preferences: ^2.0.12
  provider: ^6.1.1
  connectivity: ^3.0.6
  icons_plus: ^4.0.0
  image_picker: ^1.0.4
  contacts_service: ^0.6.3
  url_launcher: ^6.0.10
  permission_handler: ^11.3.0
  firebase_core: ^2.24.2  # Use the appropriate version
  firebase_auth: ^4.4.0
  google_sign_in: ^5.2.1
  cloud_firestore: ^4.13.1
  the_apple_sign_in: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/p1.png
    - assets/p2.png
    - assets/p3.png
    - assets/apple.png
    - assets/google.png
    - assets/bg1.png
