name: navbarhomeaboutcalculatorapp
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.12
  provider: ^6.1.1
  connectivity: ^3.0.6
  icons_plus: ^1.0.0  # Use the appropriate version
  # flutter_icons: ^1.1.0  # Correctly added flutter_icons here

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/p1.png
    - assets/p2.png
    - assets/p3.png
    - assets/apple.png
    - assets/google.png
    - assets/bg1.png
